sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.7'
  - '2.3.4'
  - '2.4.1'
  - 'ruby-head'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.9.0'
before_install:
  - gem update --system
  - gem update bundler
script: bundle exec rspec
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2.4.1'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.4.1'
      script: bundle exec travis_check_rubies
  allow_failures:
    - rvm: 'ruby-head'
