language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - ree
script: test -n "$RUBOCOP" && bundle exec rspec || bundle exec rubocop
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
