name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 3
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
        - ruby-head
        - jruby-9.1
        - jruby-9.2
      fail-fast: false
    continue-on-error: ${{ matrix.ruby == 'ruby-head' || matrix.ruby == 'jruby-9.2' }}
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - run: bundle exec rubocop
