name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 3
jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby:
        - '1.9'
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
        - jruby-9.3
        - jruby-9.4
        include:
        - ruby: ruby-head
          allow-failure: allow-failure
        - ruby: jruby-head
          allow-failure: allow-failure
      fail-fast: false
    continue-on-error: ${{ matrix.allow-failure && true || false }}
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: bundle exec rspec --format documentation
